### ISSUE TITLE
.gitignore missing?

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky-odoo-template#17]
Hello @hparfr the new copier system is all the rage, but I fill we miss our old root .gitignore file... What about putting it back?

**Comment by rvalyi** [comment]
also I see there is still an odoo/.gitignore which was pointed as useless before by @florian-dacosta https://github.com/akretion/docky-odoo-template/issues/3

Unless I miss something, I'm also in favor of trashing the inner odoo/.gitignore and getting back our root .gitignore. Typically when you start a project you want to do git init; git add . ; and start tracking your files. Without a proper .gitignore chance are you will do shit like add .env or odoo/src in the git repo or need to add every dir manually...

**Comment by hparfr** [comment]
As you wish

**Comment by bealdav** [comment]
+ 1 to add a default one even without other git files

**Comment by hparfr** [comment]
After more time to deep think about this. I propose:

/.gitignore <- for exclude .env , .db, data/*, general editor stuff  (.vimrc, .vscode, etc.)
/odoo/.gitignore <- for exclude all python  related stuff + odoo (link, src, external-src, repo.yaml, etc.)

**Comment by rvalyi** [comment]
seems ok. And yes it seems it should work https://stackoverflow.com/a/3307252
