### ISSUE TITLE
Useless odoo/.gitignore ?

### ISSUE THREAD

**Issue by florian-dacosta** [akretion/docky-odoo-template#3]
Hi, the file .gitignore in odoo repo is useless no? Because we already have a .gitignore one level higher.
If it really useless, we shoud remove it.
I just had an issue, where my src folders were ignored in my custom modules (my_module/static/src/...)
because of this. 
If it is not useless, then we should improve it to avoid this issue, but it seems useless to me!

Any thought @hparfr @rvalyi

**Comment by bealdav** [comment]
you're right
