### ISSUE TITLE
RFC branch production name

### ISSUE THREAD

**Issue by bealdav** [akretion/docky-odoo-template#58]
I have a problem with my production branch named `main`

This code is incompatible

https://github.com/akretion/docky-odoo-template/blob/ab57bec200d967fda25686296f75a8eb0e005d18/.gitlab-ci.yml.jinja#L149-L155

If all production branch had the same name, it'll be easier, don't you think ?

When you work in a project you already know what is the version.

**Comment by metaminux** [comment]
Hi @sebastienbeau and @bealdav !

Can we close this issue ? **odoo_version** is not used anymore in the corresponding rule

https://github.com/akretion/docky-odoo-template/blob/bf6d9c9ae8c087f0fe6f32135d85638a5bb2871d/src/.gitlab-ci.yml.jinja#L213-L217

**Comment by bealdav** [comment]
Akretion has a new template https://github.com/akretion/docky-odoo-template-shared for project.

Then yes we can close the issue I suppose
